distilgpt2-hftransformersv2
Azure/azureml-assets pull request #1108
Opened 2023-08-25 15:21 UTC by KonakanchiSwathi

distilgpt2-hftransformersv2

2023-08-29 12:23 UTC, novaturient95 approved these changes

2023-09-05 09:04 UTC, KonakanchiSwathi commented
job link:- failed in token classifiacation compute metrics  but proceeded with pr request 
https://ml.azure.com/experiments/id/0f020411-bbcd-4256-adcb-b55ba303a32a?wsid=/subscriptions/72c03bf3-4e69-41af-9532-dfcdc3eefef4/resourceGroups/shared-finetuning-rg/providers/Microsoft.MachineLearningServices/workspaces/v-swathikon&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

2023-09-05 12:30 UTC, novaturient95 commented
Same as gpt2 PR. Please either include all models changes in one PR and close remaining PRs or segregate to keep only the changes specific to a model mentioned in PR title

2023-09-05 12:31 UTC, novaturient95 requested changes

2023-09-05 12:31 UTC, novaturient95 commented on assets/models/system/bert-base-cased/description.md
> -    "inputs": {
Same as gpt2 PR. Please either include all models changes in one PR and close remaining PRs or segregate to keep only the changes specific to a model mentioned in PR title

2023-09-07 12:41 UTC, KonakanchiSwathi commented
closing this pr request
https://github.com/Azure/azureml-assets/pull/1181

2023-09-07 12:41 UTC, closed without merging