redeploy roberta-large with hftransformer2 flavor
Azure/azureml-assets pull request #1139
Opened 2023-08-30 13:37 UTC by choudharykartik

2023-09-07 09:20 UTC, skasturi commented
Please check gate failures

2023-09-07 09:20 UTC, skasturi requested changes
:clock1:

2023-09-07 13:01 UTC, choudharykartik commented
> Please check gate failures

@skasturi Added 'safe to test' label, now checks are passed

2023-09-11 04:51 UTC, skasturi approved these changes

2023-09-11 04:51 UTC, merged