add clip large model assets
Azure/azureml-assets pull request #1519
Opened 2023-10-19 15:47 UTC by bhimar

2023-10-19 21:31 UTC, PhaniShekhar requested changes

2023-10-19 21:31 UTC, PhaniShekhar commented on assets/models/system/openai-clip-vit-large-patch14/description.md
> +The `CLIP` model was developed by OpenAI researchers to learn about what contributes to robustness in computer vision tasks and to test the ability of models to generalize to arbitrary image classifi
image encoder part needs to be updated.

2023-10-19 21:31 UTC, PhaniShekhar commented on assets/models/system/openai-clip-vit-large-patch14/spec.yaml
> +    SHA: e6a30b603a447e251fdaca1c3056b2a16cdfebeb
This SHA needs to be updated.

2023-10-19 22:38 UTC, bhimar commented on assets/models/system/openai-clip-vit-large-patch14/spec.yaml
> +    SHA: e6a30b603a447e251fdaca1c3056b2a16cdfebeb
removed as it is not used

2023-10-19 22:41 UTC, PhaniShekhar approved these changes

2023-10-20 16:47 UTC, sharma-riti approved these changes

2023-10-20 16:49 UTC, merged