Sagoswami/prompt crafter int json fix
Azure/azureml-assets pull request #1527
Opened 2023-10-20 07:55 UTC by SamGos93

Fix the failure when output pattern has a number and the json loads fails. 
Removing the try/except logic for json loads as for chat models, we would always need the role to be added.

2023-10-20 14:48 UTC, alpatots approved these changes

2023-10-20 14:49 UTC, alpatots approved these changes

2023-10-20 14:49 UTC, alpatots commented on assets/aml-benchmark/components/src/prompt_crafter/package/prompt_factory.py
> +        if isinstance(messages, int):
Do we need a unit test?

2023-10-20 15:13 UTC, mercerchen commented
@SamGos93 Can you point me to the checksum test pipeline? Tried to find it in the checks but couldn't find it. I am assuming this would be breaking for this test.
![image](https://github.com/Azure/azureml-assets/assets/13900410/f690091c-1749-4abe-b9c1-dd9cca63aa45)

2023-10-20 18:49 UTC, mercerchen requested changes
prompt_factory line 327 to 332 would be breaking for the screenshoted case I put in the issue

2023-10-20 20:52 UTC, SamGos93 commented on assets/aml-benchmark/components/src/prompt_crafter/package/prompt_factory.py
> +        if isinstance(messages, int):
Added test cases for this.

2023-10-20 20:58 UTC, SamGos93 commented
> @SamGos93 Can you point me to the checksum test pipeline? Tried to find it in the checks but couldn't find it. I am assuming this would be breaking for this test. ![image](https://user-images.githubusercontent.com/13900410/276973743-f690091c-1749-4abe-b9c1-dd9cca63aa45.png)

@mercerchen : I have updated the logic. Can you please check?

2023-10-20 21:13 UTC, mercerchen commented
@SamGos93 Can you tell me thne name of the test pipeline? the code looks good just want to see the tests passing

2023-10-20 21:21 UTC, SamGos93 commented
> @SamGos93 Can you tell me thne name of the test pipeline? the code looks good just want to see the tests passing

It is probably this https://github.com/Azure/azureml-assets/actions/runs/6592757956/job/17914044989?pr=1527. We would know once it completes/ fails.

2023-10-22 21:31 UTC, alpatots approved these changes

2023-10-23 05:48 UTC, iamrk04 approved these changes

2023-10-23 10:00 UTC, merged