mlflow model conversion from HF for image to image task
Azure/azureml-assets pull request #1785
Opened 2023-11-20 09:07 UTC by vadthyavath

test pipelines: https://ml.azure.com/experiments/id/c41e6aae-f89c-4ccc-9d95-6c6b11572843/runs/patient_oxygen_stfxw0t4hp?wsid=/subscriptions/dbd697c3-ef40-488f-83e6-5ad4dfb78f9b/resourceGroups/rv-images-rc/providers/Microsoft.MachineLearningServices/workspaces/rv-images-ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#

2023-11-20 09:40 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +                    type=TextToImageMLFlowSchemaLiterals.INPUT_COLUMN_PROMPT_DATA_TYPE,),
```suggestion
                    type=TextToImageMLFlowSchemaLiterals.INPUT_COLUMN_PROMPT_DATA_TYPE),
```

2023-11-20 09:40 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +                    type=TextToImageMLFlowSchemaLiterals.INPUT_COLUMN_IMAGE_TYPE,)
```suggestion
                    type=TextToImageMLFlowSchemaLiterals.INPUT_COLUMN_IMAGE_TYPE)
```

2023-11-20 09:40 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +                    type=TextToImageMLFlowSchemaLiterals.OUTPUT_COLUMN_NSFW_FLAG_TYPE,),
```suggestion
                    type=TextToImageMLFlowSchemaLiterals.OUTPUT_COLUMN_NSFW_FLAG_TYPE),
```

2023-11-20 09:41 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +        """Initialize MLflow convertor for SD inpainting models."""
```suggestion
        """Initialize MLflow convertor for SD image to image models."""
```

2023-11-20 09:42 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +        """Prepare SD model for save to MLflow."""
Don't need two doc strings

2023-11-20 09:43 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/text_to_image/stable_diffusion_image_to_image_mlflow_wrapper.py
> +        return df
nit: new line at the end of the file.

2023-11-20 09:44 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +        """Return model signature for text to image models."""
```suggestion
        """Return model signature for image-text to image models."""
```

2023-11-20 09:44 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +    """MlfLow convertor base class for text to image inpainting models."""
```suggestion
    """MlfLow convertor base class for image-text to image models."""
```

2023-11-20 09:44 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +        """Initialize MLflow convertor for text to image models."""
```suggestion
        """Initialize MLflow convertor for image-text to image models."""
```

2023-11-20 09:45 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/convertors.py
> +    """HF MlfLow convertor class for stable diffusion inpainting models."""
```suggestion
    """HF MlfLow convertor class for stable diffusion image-text to image models."""
```

2023-11-21 06:26 UTC, rjaincc commented on assets/training/model_management/components/convert_model_to_mlflow/spec.yaml
> +version: 0.0.17
why are we going from 15 to 17?

2023-11-21 06:27 UTC, rjaincc commented on assets/models/system/stabilityai-stable-diffusion-xl-refiner-1-0/description.md
> +> The above summary was generated using ChatGPT. Review the <a href="https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" target="_blank">original-model-card</a> to understand the data us
The link for HF model card is pointing to the base model, should be pointing to the refiner model

2023-11-21 06:28 UTC, rjaincc commented on assets/models/system/stabilityai-stable-diffusion-xl-refiner-1-0/description.md
> +Real time|<a href="https://aka.ms/azureml-infer-sdk-image-text-to-image-generation" target="_blank">image-text-to-image-online-endpoint.ipynb</a>|<a href="https://aka.ms/azureml-infer-cli-image-text-
Are aka.ms links generated?

2023-11-21 06:29 UTC, rjaincc submitted a review, later dismissed
Approving with minor comments. Please address these before merging.

2023-11-23 06:20 UTC, vadthyavath commented on assets/training/model_management/components/convert_model_to_mlflow/spec.yaml
> +version: 0.0.17
changed to 15!

2023-11-23 11:32 UTC, MadhuM02 approved these changes

2023-11-23 16:59 UTC, MadhuM02 submitted a review, later dismissed

2023-11-24 05:55 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/text_to_image/stable_diffusion_image_to_image_mlflow_wrapper.py
> +class StableDiffusionImagetoImageMLflowWrapper(mlflow.pyfunc.PythonModel):
Let's use ImageTexttoImage / image-text-to-image for consistency

2023-11-24 05:56 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/text_to_image/config.py
> +    IMAGE_TO_IMAGE = "image-text-to-image"
I think, would be better to call it "IMAGE_TEXT_TO_IMAGE"

2023-11-24 06:03 UTC, rjaincc commented on assets/models/system/stabilityai-stable-diffusion-xl-refiner-1-0/spec.yaml
> +  task: image-text-to-image
We want to keep it "image-to-image" --> same as HuggingFace to align

2023-11-24 06:03 UTC, rjaincc requested changes
Please address the comments.

2023-11-27 05:47 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/text_to_image/config.py
> +    IMAGE_TEXT_TO_IMAGE = "image-to-image"
```suggestion
    IMAGE_TO_IMAGE = "image-to-image"
```

2023-11-27 05:48 UTC, rjaincc commented on assets/training/model_management/src/azureml/model/mgmt/processors/pyfunc/config.py
> +    IMAGE_TEXT_TO_IMAGE = "image-to-image"
```suggestion
    IMAGE_TO_IMAGE = "image-to-image"
```

2023-11-27 09:19 UTC, MadhuM02 approved these changes

2023-11-27 10:10 UTC, rjaincc approved these changes

2023-11-27 10:15 UTC, merged