Migrate batch score component
Azure/azureml-assets pull request #1882
Opened 2023-12-06 00:24 UTC by yetamsft

2023-12-08 19:47 UTC, chupadhy submitted a review, later dismissed

2023-12-08 21:26 UTC, vizhur requested changes

2023-12-08 21:44 UTC, yetamsft commented on assets/batch_score/components/driver/batch_score_components/v2/batch_score_llm/spec.yaml
> +  environment:
Updated to use the latest openmpi cpu image. Do you think if I can use it image inline like this? Or is it actually required to register this environment?

2023-12-08 21:57 UTC, vizhur commented on assets/batch_score/components/driver/batch_score_components/v2/batch_score_llm/spec.yaml
> +  environment:
you need to register an environment, and that's a bit of a process

2023-12-11 05:22 UTC, yetamsft commented on assets/batch_score/components/driver/batch_score_components/v2/batch_score_llm/spec.yaml
> +  environment:
Yeah, I started 2 separate PRs for the image/environment.

2023-12-11 21:29 UTC, yetamsft commented on assets/batch_score/components/driver/batch_score_components/v2/batch_score_llm/spec.yaml
> +  environment:
Updated to use an existing environment instead.

2023-12-11 22:01 UTC, chupadhy approved these changes

2023-12-11 22:10 UTC, vizhur approved these changes

2023-12-11 22:15 UTC, merged