add responsibleai 0.22.0 curated environment
Azure/azureml-assets pull request #191
Opened 2022-09-13 14:45 UTC by imatiach-msft

Add curated environment for raiwidgets and responsibleai 0.22 release.

Link to release notes:
https://github.com/microsoft/responsible-ai-toolbox/releases/tag/v0.22.0

2022-10-04 17:12 UTC, elesel requested changes
Would you please consider my recommendations? Looks like you're almost there.

2022-10-04 17:12 UTC, elesel commented on training/general/src/environments/responsibleai-ubuntu20.04-py38-cpu/context/conda_dependencies.yaml
> +name: sklearn-1.1
```suggestion
name: responsibleai
```

2022-10-04 17:12 UTC, elesel commented on training/general/src/environments/responsibleai-ubuntu20.04-py38-cpu/spec.yaml
> +  AzureML Responsible AI curated image.
```suggestion
  AzureML Responsible AI environment.
```

2022-10-04 17:20 UTC, imatiach-msft commented on training/general/src/environments/responsibleai-ubuntu20.04-py38-cpu/context/conda_dependencies.yaml
> +name: sklearn-1.1
done!

2022-10-04 17:20 UTC, imatiach-msft commented on training/general/src/environments/responsibleai-ubuntu20.04-py38-cpu/spec.yaml
> +  AzureML Responsible AI curated image.
done!

2022-10-04 17:23 UTC, elesel approved these changes

2022-10-05 13:37 UTC, vizhur approved these changes

2022-10-05 17:05 UTC, merged