Make index config optional in validate deployment component
Azure/azureml-assets pull request #2253
Opened 2024-02-02 19:08 UTC by jinzhaochangAtMicrosoft

2024-02-02 20:10 UTC, shpengmsft requested changes

2024-02-02 20:10 UTC, shpengmsft commented on assets/large_language_models/rag/components/validate_deployments/spec.yaml
> +    optional: false
This is optional according to -
https://msdata.visualstudio.com/Vienna/_git/AzureMlCli?path=/src/azureml-rag/src/azureml/rag/tasks/validate_deployments.py&version=GBtest1&line=648&lineEnd=649&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

2024-02-02 20:10 UTC, shpengmsft commented on assets/large_language_models/rag/components/validate_deployments/spec.yaml
> +    optional: true
Is this really optional?

how can we handle it in the code?

https://msdata.visualstudio.com/Vienna/_git/AzureMlCli?path=/src/azureml-rag/src/azureml/rag/tasks/validate_deployments.py&version=GBtest1&line=657&lineEnd=658&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

2024-02-02 23:58 UTC, shpengmsft approved these changes

2024-02-03 00:34 UTC, jingyizhu99 approved these changes

2024-02-03 00:35 UTC, merged