update latest pypi tag
Azure/azureml-assets pull request #2282
Opened 2024-02-07 07:11 UTC by nvijayrania

Using the latest-pypi tag

2024-03-05 13:38 UTC, elesel commented on scripts/azureml-assets/azureml/assets/environment/pin_package_versions.py
> +LATEST_PYPI_VERSION = re.compile(r"([^\"'\s]+?)(?:\[.*\])?([=~]=)\{\{latest-pypi-version(?::(.+))?\}\}")
There wouldn't ever be a need to match `[]`
```suggestion
LATEST_PYPI_VERSION = re.compile(r"([^\"'\s]+?)(?:\[.+\])?([=~]=)\{\{latest-pypi-version(?::(.+))?\}\}")
```

2024-03-05 15:02 UTC, nvijayrania commented
@elesel Thanks for taking a look at it. Could you please share the release process for the azureml-assets package. Actually I haven't worked with it before. Is there any release cadence with which this change can be released?

2024-03-05 15:04 UTC, elesel commented
@nvijayrania The release process is automatic. Please update those two files and when the PR is merged the package will be updated in PyPI.

2024-03-05 15:53 UTC, nvijayrania commented
Thanks @elesel : updated the PR.

2024-03-05 16:16 UTC, elesel requested changes

2024-03-05 16:16 UTC, elesel commented on scripts/azureml-assets/CHANGELOG.md
> +- [#2407](https://github.com/Azure/azureml-assets/pull/2282) Add support for extra in LATEST_PYPI_VERSION env var
```suggestion
## 1.16.36 (2023-03-05)
### 🐛 Bugs Fixed
- [#2282](https://github.com/Azure/azureml-assets/pull/2282) Add support for optional dependencies with `latest-pypi-version`

```

2024-03-05 18:43 UTC, elesel approved these changes

2024-03-06 05:24 UTC, rjaincc approved these changes

2024-03-06 05:24 UTC, merged