Added environment sklearn-1.5
Azure/azureml-assets pull request #3117
Opened 2024-07-03 23:12 UTC by jeff-shepherd

2024-07-16 17:44 UTC, vizhur commented on assets/training/general/environments/sklearn-1.5/context/conda_dependencies.yaml
> +- conda-forge
please make conda-forge first

2024-07-16 17:44 UTC, vizhur commented on assets/training/general/environments/sklearn-1.5/context/conda_dependencies.yaml
> +  # vulnerabilities
remove this, it should be solved with dependencies from conda-forge

2024-07-16 17:45 UTC, vizhur requested changes
please update conda yaml with the comments

2024-07-17 17:57 UTC, jeff-shepherd commented
> please update conda yaml with the comments

2024-07-17 18:05 UTC, jeff-shepherd commented
> please update conda yaml with the comments

Done

2024-07-17 18:37 UTC, vizhur approved these changes

2024-07-17 18:43 UTC, merged