MaaP Component changes - transformers 4.44.0
Azure/azureml-assets pull request #3250
Opened 2024-08-12 16:20 UTC by Anubha98

Changes:
1. version upgrade for components
    - Command components : 0.0.56 --> 0.0.57
    - Pipeline components: 0.0.58 --> 0.0.59
2. Script changes for model_converter_adapters.py for t5 models for translation, summarization to avoid copying base model dependencies
3. Environment upgrade to 0.0.65
4. Remove all task specific converters and kept common converter only - corresponding changes to pipeline yamls

2024-08-13 10:28 UTC, chiragbhatt311 submitted a review, later dismissed

2024-08-14 05:07 UTC, ghsutirtha submitted a review, later dismissed

2024-08-14 05:14 UTC, skanakamedal approved these changes

2024-08-14 05:15 UTC, skanakamedal requested changes

2024-08-14 05:15 UTC, skanakamedal commented on validation_rules.json
> +}
Revert this change

2024-08-19 06:13 UTC, Anubha98 commented on validation_rules.json
> +}
Reverted

2024-08-27 06:00 UTC, ashg1910 approved these changes

2024-08-27 06:03 UTC, aggarwal-k approved these changes

2024-08-27 06:18 UTC, skanakamedal approved these changes

2024-08-27 06:19 UTC, merged