Add rad-dino spec
Azure/azureml-assets pull request #3658
Opened 2024-12-09 09:02 UTC by roopavidhya

Add rad-dino spec

2024-12-09 09:08 UTC, Addi-11 submitted a review, later dismissed

2024-12-09 13:09 UTC, Addi-11 reviewed
Add the MLmodel file for the model as well.

2024-12-12 06:07 UTC, Addi-11 approved these changes

2024-12-12 06:38 UTC, utkshukla requested changes

2024-12-12 06:48 UTC, utkshukla approved these changes

2024-12-12 06:48 UTC, merged