Add LLama Models
Azure/azureml-assets pull request #716
Opened 2023-06-02 12:21 UTC by ankushbhatia2

2023-06-02 12:37 UTC, vizhur requested changes

2023-06-02 12:37 UTC, vizhur commented on models/system/openlm-research-open_llama_3b_350bt_preview/asset.yaml
> +categories: ["Models"]
Models of category models is not a best choice

2023-06-02 12:47 UTC, jpmann commented on models/system/openlm-research-open_llama_3b_350bt_preview/spec.yaml
> +  finetuning-tasks: text-classification, token-classification, question-answering
I don't think LLama supports all the 3 tasks.

2023-06-02 12:47 UTC, jpmann commented on models/system/openlm-research-open_llama_7b_400bt_preview/spec.yaml
> +  finetuning-tasks: text-classification, token-classification, question-answering
Need to check on the finetune tasks

2023-06-14 08:02 UTC, sarthaks95 approved these changes

2025-01-08 18:15 UTC, closed without merging